name: FT STATUS CHECKS

on:
  workflow_call:
    inputs:
      ft-pr-status:
        description: "Status of the FT on PR deploy and test"
        type: string
      ft-pr-emoji:
        description: "Status EMOJI for FT on PR deploy and test"
        type: string

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github Job"
          echo "-----------------------------------------------------------------------------------------------------------"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "-----------------------------------------------------------------------------------------------------------"
          # looping in case we want to add more checks later
          for i in ${{ inputs.ft-pr-status }}; do
            if [ $i == completed_passed ]; then
              echo "======================================"
              echo "Status checks completed successfully"
              echo "======================================"
            elif [ $i == completed_failed ]; then
              echo "======================================"
              echo "One or more status checks failed"
              echo "======================================"
              exit 1
            elif [ $i == cancelled ]; then
              echo "========================================"
              echo "One or more status checks were cancelled"
              echo "========================================"
              exit 1
            elif [ $i == skipped_passed_prior ]; then
              echo "========================================================================"
              echo "FT skipped - [passed] previously ran successfully on the current commit"
              echo "========================================================================"
            elif [ $i == skipped_dockerfile ]; then
              echo "=================================="
              echo "FT skipped - Dockerfile missing"
              echo "=================================="
            elif [ $i == skipped_build_system ]; then
              echo "======================================="
              echo "FT skipped - unsupported build system"
              echo "======================================="
            elif [ $i == skipped_dependabot ]; then
              echo "========================================================================"
              echo "FT skipped - Dependabot FT disabled"
              echo "========================================================================"
            elif [ $i == skipped_failed_prior ]; then
              echo "==================================================================="
              echo "FT skipped - [failed] never ran successfully on the current commit"
              echo "==================================================================="
              exit 1
            elif [ $i == unexpected ]; then
              echo "=============================================="
              echo "FT skipped - [failed] skipped unexpectedly"
              echo "=============================================="
              exit 1
            fi
          done

  comment-pt:
    runs-on: ubuntu-latest
    needs: status-check
    if: always() && github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]'  
    steps:
      - run: |
          touch status.md
          echo "### FT STATUS CHECKS :rocket: :eyes:" >> status.md
          echo '**Status Checks for the Functional Test run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**' >> status.md
          echo "| _Jobs_             | _Status Check_          |" >> status.md
          echo "|:------------------:|:-----------------------:|" >> status.md
          echo '| Functional Tests   | ${{ inputs.ft-pr-emoji }} `${{ inputs.ft-pr-status }}` |' >> status.md
          cat status.md

      - name: Comment PR with execution number
        uses: glcp/actions-comment-pull-request@v2
        with:
          filePath: ./status.md
          comment_tag: FT Status Checks
