name: PR QUALITY CHECK STATUS CHECKS

on:
  workflow_call:
    inputs:
      copyright-check:
        description: "Status of the copyright check"
        type: string
      secret-scanner:
        description: "Status of the secret scanner"
        type: string
      malware-scanner:
        description: "Status of the malware scanner"
        type: string
      pr-validation:
        description: "Status of the Jira pr validation"
        type: string
      post-check:
        description: "Status of consolidated custom post-checks"
        type: string

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github Job"
          echo "-----------------------------------------------------------------------------------------------------------"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "-----------------------------------------------------------------------------------------------------------"

          for i in ${{ inputs.copyright-check }} ${{ inputs.secret-scanner }} ${{ inputs.malware-scanner }} ${{ inputs.pr-validation }} ${{ inputs.post-check }}
          do
          if [ $i == success ]; then
            echo "======================================"
            echo "Status checks completed successfully"
            echo "======================================"
          elif [ $i == skipped ]; then
            echo "======================================"
            echo "One or more status checks skipped"
            echo "======================================"
          elif [ $i == failure ]; then
            echo "======================================"
            echo "One or more status checks failed"
            echo "======================================"
            exit 1
          elif [ $i == cancelled ]; then
            echo "========================================="
            echo "One or more status checks were cancelled "
            echo "========================================="
            exit 1
          fi
          done

  comment-pt:
    runs-on: ubuntu-latest
    needs: status-check
    if: always() && github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]'  
    steps:
      - run: |
          touch status.md
          echo "### PR QUALITY CHECK STATUS CHECKS :rocket: :eyes:" >> status.md
          echo '**Quality Check Status Checks for the PR run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**' >> status.md
          echo "| _Jobs_          | _Status Check_                  |" >> status.md
          echo "|:---------------:|:-------------------------------:|" >> status.md
          echo '| Copyright Check | `${{ inputs.copyright-check }}` |' >> status.md
          echo '| Secret Scan     | `${{ inputs.secret-scanner }}`  |' >> status.md
          echo '| Malware Scan    | `${{ inputs.malware-scanner }}` |' >> status.md
          if [ '${{ inputs.pr-validation }}' != 'skipped' ]; then
            echo '| PR Validation | `${{ inputs.pr-validation }}`   |' >> status.md
          fi
          echo '| Post Check      | `${{ inputs.post-check }}` |' >> status.md

          cat status.md

      - name: Comment PR with execution number
        uses: glcp/actions-comment-pull-request@v2
        with:
          filePath: ./status.md
          comment_tag: PR Quality Check Status Checks
