name: PR LINT AND TEST STATUS CHECKS

on:
  workflow_call:
    inputs:
      lint:
        description: "Status of the lint job"
        type: string
      unit-test:
        description: "Status of the unit test job"
        type: string

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github Job"
          echo "-----------------------------------------------------------------------------------------------------------"
          echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "-----------------------------------------------------------------------------------------------------------"

          for i in ${{ inputs.lint }} ${{ inputs.unit-test }}
          do
          if [ $i == success ]; then
            echo "======================================"
            echo "Status checks completed successfully"
            echo "======================================"
          elif [ $i == skipped ]; then
            echo "======================================"
            echo "One or more status checks skipped"
            echo "======================================"
          elif [ $i == failure ]; then
            echo "======================================"
            echo "One or more status checks failed"
            echo "======================================"
            exit 1
          elif [ $i == cancelled ]; then
            echo "========================================="
            echo "One or more status checks were cancelled "
            echo "========================================="
            exit 1
          fi
          done

  comment-pt:
    runs-on: ubuntu-latest
    needs: status-check
    if: always() && github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]'  
    steps:
      - run: |
          touch status.md
          echo "### PR LINT AND TEST STATUS CHECKS :rocket: :eyes:" >> status.md
          echo '**Lint and Test Status Checks for the PR run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}**' >> status.md
          echo "| _Jobs_          | _Status Check_                  |" >> status.md
          echo "|:---------------:|:-------------------------------:|" >> status.md
          echo '| Linting         | `${{ inputs.lint }}`           |' >> status.md
          echo '| Unit Tests      | `${{ inputs.unit-test }}`       |' >> status.md

          cat status.md

      - name: Comment PR with execution number
        uses: glcp/actions-comment-pull-request@v2
        with:
          filePath: ./status.md
          comment_tag: Lint and Test PR Status Checks
